### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException: length=1; index=1

### ISSUE THREAD

**Issue by Michenux** [chrisbanes/PhotoView#72]
hi,

I try to use your library but i have the exception bellow when zoom in.
```
08-30 22:44:43.437  20210-20210/com.******E/AndroidRuntime: FATAL EXCEPTION: main
        java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1004)
        at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:855)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1852)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2209)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1952)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2209)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1952)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2209)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1952)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1966)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1418)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2424)
        at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.dispatchTouchEvent(ActionBarActivityDelegateICS.java:255)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1914)
        at android.view.View.dispatchPointerEvent(View.java:7564)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3883)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3778)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5419)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5399)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5370)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5493)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:182)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:174)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5472)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5512)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
        at android.view.Choreographer.doCallbacks(Choreographer.java:562)
        at android.view.Choreographer.doFrame(Choreographer.java:530)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
        at android.os.Handler.handleCallback(Handler.java:730)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by bhatnagar-gaurav** [comment]
Since this issue again reappeared from 1.2.3 and it is still persisting in the latest version, when a fix will be updated

**Comment by Jawnnypoo** [comment]
Since this is a framework issue, the fix for now is to extend the problematic ViewGroup and catch the exception. See the README for more

**Comment by pwgn** [comment]
I keep getting the ArrayIndexOutOfBoundsException even though I've implemented the fix described in [smareks comment](https://github.com/chrisbanes/PhotoView/issues/72#issuecomment-24494046).

I can see that the my ImageView is part of the HackyDrawerLayout and that the onInterceptTouchEvent in that class is run at times, but the exception is never catched when the exception occur. 

This is my `onInterceptTouchEvent`:

```java
    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        try {
            return super.onInterceptTouchEvent(ev);
        } catch (ArrayIndexOutOfBoundsException e) {
            e.printStackTrace();
            return false;
        }
    }
```


And my xml file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<co.legacyventures.intreact.HackyDrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <ProgressBar
            android:id="@+id/progress_bar"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerHorizontal="true"
            android:layout_centerVertical="true" />

        <ImageView
            android:id="@+id/image_view_image_display"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <android.support.design.widget.CoordinatorLayout
            android:id="@+id/snackbar"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </RelativeLayout>

</co.legacyventures.intreact.HackyDrawerLayout>
```

Any ideas?

**Comment by gabrieljuan** [comment]
I've got the error just now, same with @pwgn . but if you set the ImageView width and height to wrap_content, the error won't appear.

**Comment by Montanax** [comment]
Well I have the same problem and all the solutions and workaround didn't work without all kinds of other problems (like unresponsiveness). For now I chose a solution where my FrameLayout fragment container containing the PhotoViews is a different one outside my CoordinatorLayout altogether. This way the error can never occur because it's essentially a normal FrameLayout not wrapped around any other layouts.

**Comment by TasneemBohra** [comment]
I am still facing this error on Galaxy S DUOS (kyleopen) Android 4.0.3 - 4.0.4. Any resolution ?

**Comment by SrishtiRoy** [comment]
will this photoView only works for  a list of images?
